### ISSUE TITLE
Last firmware 2.74 issues

### ISSUE THREAD

**Issue by MercurioX85** [Ansem-SoD/Picofly#16]
what is the problem if you install firmware 2.74?  why was it archived?

**Comment by deejay87** [comment]
v2.74 + 300 mhz precision rp2040 >> may be not stable at 300mhz

**Comment by Roy0002** [comment]
Updating frimware burnt fuse?

**Comment by postnutcIarity** [comment]
> v2.74 + 300 mhz precision rp2040 >> may be not stable at 300mhz

what do you mean exactly by this?
