### ISSUE TITLE
Error code not listed

### ISSUE THREAD

**Issue by aqw00** [Ansem-SoD/Picofly#19]
https://github.com/Ansem-SoD/Picofly/assets/11737201/2b352f32-cbd5-4bac-8cd1-96f3a2963d12

My switch just starts normally. I also can't find the error (\*=\*) in the list. Can someone help me please?

**Comment by Quas7** [comment]
also have the pattern: \*=\* ... adding 47Ohm did now change to \*\* (RST "B" not connected)... will investigate further tomorrow.

@aqw00 did you resolve the issue? I noticed, that you placed 470Ohm instead of 47Ohm on the lines.

Update (from the PicoFlyGuideV.6.2):
```
*** No eMMC CMD1 responce (bad eMMC?)
**= No eMMC block 1 read (should not happen)
*=* No eMMC block 0 read (eMMC init failure?)
*== No eMMC CMD1 request (poor wiring, or dead CPU)
```
