### ISSUE TITLE
Please remove outdated and semi-dangerous firmwares, or at least move them to the archive?

### ISSUE THREAD

**Issue by lightninjay** [Ansem-SoD/Picofly#2]
People are continually flashing the 2.5 + unlock file, which by name would seem like the right one to flash, but the newest firmware has now gotten up to 2.65, and that firmware usually fails to unlock, and won't allow for updating from PicoFly toolbox.

Please remove/archive the older firmwares, and update the repository to the latest firmware.

**Comment by Ansem-SoD** [comment]
Done. Wasn't home for a while to update
