### ISSUE TITLE
Mariko, HWFLY RP2040 core, 2.74, issue, random booting to black screen and left joycon does not dock

### ISSUE THREAD

**Issue by datapaganism** [Ansem-SoD/Picofly#23]
Mariko V2
HWFLY RP2040 core on 2.74,
random booting to black screen when the device is off and left joycon does not dock anymore making handheld mode impossible

**Comment by Ansem-SoD** [comment]
check your connector for the joycon rail

**Comment by datapaganism** [comment]
Yes I have and it is fine, it is not the controllers fault either.

I had another person say they had the same issue but their response was
deleted on gbatemp because they wrote in spanish

**Comment by datapaganism** [comment]
I've had my V2 repaired with another picofly but it started exhibiting the same issues, I believe the CPU got fried from the install.

I ended up getting an entire mainboard replacement.
