### ISSUE TITLE
Picofly Boots to Ofw

### ISSUE THREAD

**Issue by Christianacqua** [Ansem-SoD/Picofly#24]
Picofly flashes a blue light then 4 yellow lights and boots to ofw, how to fix this? Picofly FW 2.73

**Comment by Christianacqua** [comment]
FIxed it by restarting while pressing vol+

**Comment by 1stdevfriend** [comment]
I'm trying the same thing but it's still going directly into ofw. How did you do it? @Christianacqua

**Comment by aodaru** [comment]
> Picofly flashes a blue light then 4 yellow lights and boots to ofw, how to fix this? Picofly FW 2.73

The 4 light was long short long short? Do you not remember?
