### ISSUE TITLE
Purple screen on SK hynix EMMC

### ISSUE THREAD

**Issue by dewolft** [Ansem-SoD/Picofly#3]
hello guys, i've install a picofly on OLED switch, it boot ok into HEKATE but when i try to create emuMMC go in EMMC INIT ERROR, if i try to start OFW it go in PURPLE SCREEN (kernel panic). 

so i've removed picofly, install an HWFLY and everything gone fine... and also OFW boot normally... 

what can be? (i can suppose is the bootloader maybe that chip install during training?)

i can't test the 2.5 since there isn't the update.bin file (how can i create it?)
i've tried FW versione 2.61 and 2.65, same result
i've put 47 Ohm resistor (on point A,C,D)

EMMC is SK hynix 

let me know if i can provide some info to make a better firmware :)

**Comment by Ansem-SoD** [comment]
Hi, you are best off asking on gbatemp. I just re-host files here.

**Comment by dewolft** [comment]
thansk dude, i did it also there :)
