### ISSUE TITLE
error code *=*(short long short)

### ISSUE THREAD

**Issue by fesily** [Ansem-SoD/Picofly#32]
Switch lite get the error code. 
I don't have any idea about this problem.
Data0: 0.480
3.3v: 0.398
CMD: 0.515
CLK: 0.530
RST: 0.440
This is what I measured on the 2040 motherboard

**Comment by fesily** [comment]
I've replaced 3 motherboards and it works perfectly fine on other switch lites

**Comment by Quas7** [comment]
EMMC init fails.
What do you get on CPU?
Try to clean all flux residue again maybe.

**Comment by radius611** [comment]
I have this error code as well on V1 switch. I have tried making sure my board is as clean as possible. I've checked the CPU solder joints as well.  Switch boots fine if eMMC is directly connect, but won't boot with picofly. I've tried 2.73 and 2.7.5.

**Comment by hanswurst31** [comment]
i also have this problem on patched erista. everything looks smooth. tried another picofly. same error. wonder if the flex cable is faulty?

**Comment by fesily** [comment]
I found the season， emmc is gone，sad
