### ISSUE TITLE
When the console its completely turned off and i plug the console to the charger/dock it runs the payload.

### ISSUE THREAD

**Issue by turron65** [Ansem-SoD/Picofly#43]
As the title says when the console its completely turned off and i plug the console to the charger/dock it runs hekate, even when i turn it off using hekate.
Is this an intentional behavior? If so, there's a way to config that? Thanks :)

**Comment by thelegendaryjohn** [comment]
Sadly no. It's an intended behavior of the Switch, it will always turn on if you plug in the charger/dock it. A workaround is that you power it off **after** plugging it in. But if there's no reason why you would want to shut it down, there's no need to really, sleep mode is designed to barely drain the battery at all

Now if you're afraid of forgetting about that, which will leave your Switch in Hekate (it won't turn off, bad for battery and screen of course), you can set up auto boot, so it will automatically boot into Atmosphère, and engage sleep mode shortly after, like how the Switch should work! :)
