### ISSUE TITLE
Last update 2.72 does not update 

### ISSUE THREAD

**Issue by curcius** [Ansem-SoD/Picofly#5]
I can't do the update by picofly payload it says it loaded the update.bin but when I restart the switch it restarts in ofw and the chip is flashing white, I restart and it gives the glich but it continues in the previous version in case 2.67. How should I do to update? only by usb? 

[Video](https://youtu.be/ZwPodD8u_NM)

**Comment by Ansem-SoD** [comment]
This might be silly but did you use the latest update.bin?

**Comment by drty2k** [comment]
i have same problem, try many times - after power off it booting ofw, after next reboot glitch work fine but firmware stay same = 2.67

**Comment by curcius** [comment]
> i have same problem, try many times - after power off it booting ofw, after next reboot glitch work fine but firmware stay same = 2.67

Yes I downloaded the latest update.bin

**Comment by drty2k** [comment]
get update.bin from this place and all work fine)
https://gbatemp.net/threads/picofly-a-hwfly-switch-modchip.622701/page-78#post-10090767

**Comment by mistervampi** [comment]
Same here!! Even with GBATemp BIN
V2 with Kioxia (Toshiba) NAND

**Comment by curcius** [comment]
> get update.bin from this place and all work fine) https://gbatemp.net/threads/picofly-a-hwfly-switch-modchip.622701/page-78#post-10090767

I did the gbatemp procedure and it worked but I did two more steps to make it work 

-show firmware information
- update firmware from SD card (place update.bin into the root folder)
- rollback to the backup firmware slot
- reset learning statistics
- dump / write sdloader
- back to hekate
- shutdown the consol for the hekate
- and 2.72 updated 

😃

**Comment by curcius** [comment]
> get update.bin from this place and all work fine) https://gbatemp.net/threads/picofly-a-hwfly-switch-modchip.622701/page-78#post-10090767

Thank you so much

**Comment by curcius** [comment]
Sorted out

**Comment by curcius** [comment]
Solved

**Comment by ad1095445** [comment]
Bro,i am in 2.65,and i want upate to 2.8. it's always faild ,and firmware info show "Fuse count 0".what should i do.
