### ISSUE TITLE
*=* short long short error message

### ISSUE THREAD

**Issue by DnkMemes** [Ansem-SoD/Picofly#53]
Installed the modchip, measured each solder point with a meter and found that they were all the proper values. Checked each solder point for any form of short and found none. Powered on switch and was met with *=* short long short error message.

**Comment by betamoon1** [comment]
Same issue, you solved it?

**Comment by DnkMemes** [comment]
I just ended up redoing the soldering on each connection and that ended up fixing it. Maybe just a cold solder joint?
