### ISSUE TITLE
2.72 does not work 

### ISSUE THREAD

**Issue by setryky** [Ansem-SoD/Picofly#9]
when i use the 2.72 version, i only get 2 long pulses, indicating bad clk. However, the solder is good, and when i downgraded to 2.67, it worked fine (i soldered a usb cable to the rp2040). Before downgrading to 2.67, i tested another rp2040 and got the same thing, so i think the problem is the 2.72 version. Any hints to what can i do, other than downgrade?

**Comment by Ansem-SoD** [comment]
updated to 2.73 error codes are in changelog.md
